"""Cheering Sign"""

def main():
    """function cheer"""
    name_1 = input()
    name_2 = input()
    name_3 = input()
    print("************")
    print("* Fighting *")
    print("* %8.8s *"%name_1)
    print("************")
    print("     ||")
    print("     ||")
    print("     ||")
    print("************")
    print("* Fighting *")
    print("* %8.8s *"%name_2)
    print("************")
    print("     ||")
    print("     ||")
    print("     ||")
    print("************")
    print("* Fighting *")
    print("* %8.8s *"%name_3)
    print("************")
    print("     ||")
    print("     ||")
    print("     ||")
main()
