"""DocString"""
print("         *")
print("        * *")
print("       * * *")
print("      * *** *")
print("     * Sunny *")
print("    * ******* *")
print("   * ********* *")
print("  * *********** *")
print(" *               *")
print("*******************")
print("illuminaticonfirmed")
